const SAVE_OPTION = "SAVE_OPTION";
const POPUP_GET_LIST_OF_PASSCARDS = "POPUP_GET_LIST_OF_PASSCARDS";
const PASTE_PASSCARD_TO_FORM = "PASTE_PASSCARD_TO_FORM";
const GET_PROFILE = "GET_PROFILE";
const LOGOUT = "LOGOUT";
